### ISSUE TITLE
Improve the description of how to use the GIT integration

### ISSUE THREAD

**Issue by bergel** [ronsaldo/pharo-git-thermite#6]
- Add a description in `README.md` how to use the menu `Visualize local commit` and `Visualize pull request`
- Why not a video?

**Comment by ronsaldo** [comment]
Pull request example: https://youtu.be/f196btLfYxM

**Comment by ronsaldo** [comment]
Local commit example: https://youtu.be/LCHTiJ4nx3g

**Comment by ronsaldo** [comment]
I added links into the video examples in the README.md
